// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentCoursesApi.Data;

#nullable disable

namespace StudentCoursesApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260427200149_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentCoursesApi.Models.CourseRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompletionStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("CourseCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CreditHours")
                        .HasColumnType("int");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("StudentProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentProfileId");

                    b.ToTable("CourseRecords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompletionStatus = "Completed",
                            CourseCategory = "Major",
                            CourseCode = "IT-2045C",
                            CourseName = "Programming II",
                            CreditHours = 3,
                            Semester = "Spring 2025",
                            StudentProfileId = 1
                        },
                        new
                        {
                            Id = 2,
                            CompletionStatus = "Completed",
                            CourseCategory = "Major",
                            CourseCode = "IT-3045C",
                            CourseName = "Client-Side Web Programming",
                            CreditHours = 3,
                            Semester = "Summer 2025",
                            StudentProfileId = 1
                        },
                        new
                        {
                            Id = 3,
                            CompletionStatus = "In Progress",
                            CourseCategory = "Major",
                            CourseCode = "IT-2035C",
                            CourseName = "Network Infrastructure Management",
                            CreditHours = 3,
                            Semester = "Spring 2026",
                            StudentProfileId = 1
                        },
                        new
                        {
                            Id = 4,
                            CompletionStatus = "Planned",
                            CourseCategory = "Elective",
                            CourseCode = "JAPN-2001",
                            CourseName = "Second-Year Japanese 1",
                            CreditHours = 5,
                            Semester = "Fall 2026",
                            StudentProfileId = 1
                        },
                        new
                        {
                            Id = 5,
                            CompletionStatus = "Completed",
                            CourseCategory = "Major",
                            CourseCode = "CS-1021C",
                            CourseName = "Computer Science I",
                            CreditHours = 3,
                            Semester = "Fall 2025",
                            StudentProfileId = 2
                        },
                        new
                        {
                            Id = 6,
                            CompletionStatus = "Completed",
                            CourseCategory = "General Education",
                            CourseCode = "MATH-1062",
                            CourseName = "Calculus II",
                            CreditHours = 3,
                            Semester = "Fall 2025",
                            StudentProfileId = 2
                        },
                        new
                        {
                            Id = 7,
                            CompletionStatus = "In Progress",
                            CourseCategory = "Major",
                            CourseCode = "CS-2028C",
                            CourseName = "Data Structures",
                            CreditHours = 3,
                            Semester = "Spring 2026",
                            StudentProfileId = 2
                        },
                        new
                        {
                            Id = 8,
                            CompletionStatus = "In Progress",
                            CourseCategory = "Elective",
                            CourseCode = "FREN-1001",
                            CourseName = "Basic French I",
                            CreditHours = 5,
                            Semester = "Spring 2026",
                            StudentProfileId = 2
                        },
                        new
                        {
                            Id = 9,
                            CompletionStatus = "Completed",
                            CourseCategory = "Major",
                            CourseCode = "ECON-1001",
                            CourseName = "Introduction to Microeconomics",
                            CreditHours = 3,
                            Semester = "Fall 2025",
                            StudentProfileId = 3
                        },
                        new
                        {
                            Id = 10,
                            CompletionStatus = "In Progress",
                            CourseCategory = "Major",
                            CourseCode = "ECON-1002",
                            CourseName = "Introduction to Macroeconomics",
                            CreditHours = 3,
                            Semester = "Spring 2026",
                            StudentProfileId = 3
                        },
                        new
                        {
                            Id = 11,
                            CompletionStatus = "In Progress",
                            CourseCategory = "Elective",
                            CourseCode = "SPAN-1001",
                            CourseName = "Basic Spanish I",
                            CreditHours = 5,
                            Semester = "Spring 2026",
                            StudentProfileId = 3
                        },
                        new
                        {
                            Id = 12,
                            CompletionStatus = "Completed",
                            CourseCategory = "Major",
                            CourseCode = "MATH-1062",
                            CourseName = "Calculus II",
                            CreditHours = 4,
                            Semester = "Spring 2025",
                            StudentProfileId = 4
                        },
                        new
                        {
                            Id = 13,
                            CompletionStatus = "Completed",
                            CourseCategory = "Major",
                            CourseCode = "MATH-2063",
                            CourseName = "Multivariable Calculus",
                            CreditHours = 4,
                            Semester = "Fall 2025",
                            StudentProfileId = 4
                        },
                        new
                        {
                            Id = 14,
                            CompletionStatus = "Completed",
                            CourseCategory = "Elective",
                            CourseCode = "FAM-2050",
                            CourseName = "Japanese Pop, Anime, and Video Game Music",
                            CreditHours = 3,
                            Semester = "Fall 2025",
                            StudentProfileId = 4
                        },
                        new
                        {
                            Id = 15,
                            CompletionStatus = "Completed",
                            CourseCategory = "Major",
                            CourseCode = "NBSN-1101",
                            CourseName = "Introduction to Professional Nursing",
                            CreditHours = 3,
                            Semester = "Fall 2025",
                            StudentProfileId = 5
                        },
                        new
                        {
                            Id = 16,
                            CompletionStatus = "In Progress",
                            CourseCategory = "Major",
                            CourseCode = "NBSN-2101C",
                            CourseName = "Fundamentals of Patient Centered Care",
                            CreditHours = 6,
                            Semester = "Spring 2026",
                            StudentProfileId = 5
                        },
                        new
                        {
                            Id = 17,
                            CompletionStatus = "Completed",
                            CourseCategory = "Elective",
                            CourseCode = "PSY-1001",
                            CourseName = "Introduction to Psychology",
                            CreditHours = 3,
                            Semester = "Fall 2026",
                            StudentProfileId = 5
                        });
                });

            modelBuilder.Entity("StudentCoursesApi.Models.StudentProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CollegeProgram")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FavoriteElectiveCourse")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FavoriteMajorCourse")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("YearInProgram")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("StudentProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CollegeProgram = "Information Technology",
                            FavoriteElectiveCourse = "Second-Year Japanese 1",
                            FavoriteMajorCourse = "Programming II",
                            FullName = "Joshua Hampton",
                            YearInProgram = "Sophomore"
                        },
                        new
                        {
                            Id = 2,
                            CollegeProgram = "Computer Science",
                            FavoriteElectiveCourse = "Basic French I",
                            FavoriteMajorCourse = "Data Structures",
                            FullName = "Alex Morgan",
                            YearInProgram = "Sophomore"
                        },
                        new
                        {
                            Id = 3,
                            CollegeProgram = "Economics",
                            FavoriteElectiveCourse = "Basic Spanish I",
                            FavoriteMajorCourse = "Macroeconomics",
                            FullName = "Taylor Reed",
                            YearInProgram = "Freshman"
                        },
                        new
                        {
                            Id = 4,
                            CollegeProgram = "Mathematics",
                            FavoriteElectiveCourse = "Japanese Pop, Anime, and Video Game Music",
                            FavoriteMajorCourse = "Calculus III",
                            FullName = "Jordan Blake",
                            YearInProgram = "Junior"
                        },
                        new
                        {
                            Id = 5,
                            CollegeProgram = "Nursing",
                            FavoriteElectiveCourse = "Introduction to Psychology",
                            FavoriteMajorCourse = "Fundamentals of Patient Centered Care",
                            FullName = "Casey Nguyen",
                            YearInProgram = "Sophomore"
                        });
                });

            modelBuilder.Entity("StudentCoursesApi.Models.CourseRecord", b =>
                {
                    b.HasOne("StudentCoursesApi.Models.StudentProfile", "StudentProfile")
                        .WithMany("CourseRecords")
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("StudentCoursesApi.Models.StudentProfile", b =>
                {
                    b.Navigation("CourseRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
